#!/usr/bin/env python3
"""Regenerate the credits page's data from a retransmission checkout.

Usage: _scripts/update-credits.py path/to/retransmission

Reads the checkout's AUTHORS file, whose sections look like:

    Maintainers
      Some Maintainer (@github-handle)

and writes _data/authors.json, keeping each section's order.

Reads the checkout's TRANSLATORS file, which looks like:

    German (de)
      Lead Translator (lead)
      Client Lead (macOS lead)
      Some Contributor

and writes _data/translators.json: languages sorted by name,
each with its leads first and the other translators alphabetical.
"""

import json
import pathlib
import re
import sys
import unicodedata

SITE = pathlib.Path(__file__).resolve().parent.parent
DATA = SITE / "_data"
NOTE = "Generated by _scripts/update-credits.py from the retransmission repo's {} file. Edit that file, not this one."

AUTHOR = re.compile(r"^(?P<name>.+?)(?: \(@(?P<github>[\w-]+)\))?$")

LANGUAGE = re.compile(r"^(?P<name>\S.*) \((?P<code>[a-z]{2,3}(?:_[A-Za-z0-9]+)?(?:@[a-z]+)?)\)$")
LEAD_ROLES = ["lead", "GTK lead", "Qt lead", "macOS lead"]
LEAD_ROLE = {role.casefold(): role for role in LEAD_ROLES}
LEAD = re.compile(rf"^(?P<name>.+?) \((?P<role>{'|'.join(map(re.escape, LEAD_ROLES))})\)$", re.IGNORECASE)

# Letters that NFKD doesn't split into a base letter and marks.
# Keep in sync with `letters` in credits/index.html.
LETTERS = str.maketrans({"ł": "l", "ø": "o", "đ": "d", "ð": "d", "æ": "ae", "œ": "oe", "ı": "i", "þ": "th", "ħ": "h"})


def collation_key(text):
    """Sort case- and accent-insensitively, so "Émile" files under E and "Łukasz" under L."""
    decomposed = unicodedata.normalize("NFKD", text.casefold())
    base = "".join(c for c in decomposed if not unicodedata.combining(c))
    return base.translate(LETTERS), text


def parse_authors(path):
    """Each unindented heading followed by indented names is a section.
    Prose, and headings ending in ':' (the pre-4.0 contributors paragraph), are skipped."""
    sections = []
    current = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        if not line[0].isspace():
            heading = line.strip()
            current = None if heading.endswith(":") else {"section": heading, "people": []}
            if current:
                sections.append(current)
        elif current is not None:
            current["people"].append(AUTHOR.match(line.strip()).groupdict())
    sections = [s for s in sections if s["people"]]
    if not sections:
        sys.exit(f"{path}: no sections found")
    return sections


def parse_translators(path):
    languages = {}
    current = None
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        if not line[0].isspace():
            if match := LANGUAGE.match(line.rstrip()):
                current = languages.setdefault(match["code"], {
                    "language": match["name"], "code": match["code"],
                    "leads": {}, "translators": set(),
                })
            elif languages:
                # Past the preamble, so this is a malformed heading.
                # Skipping it would silently drop its translators.
                sys.exit(f"{path}:{number}: expected a language heading like 'German (de)'")
            continue
        if current is None:
            continue  # indented text in the file's preamble
        name = line.strip()
        if match := LEAD.match(name):
            current["leads"].setdefault(match["name"], set()).add(LEAD_ROLE[match["role"].casefold()])
        else:
            current["translators"].add(name)
    if not languages:
        sys.exit(f"{path}: no languages found")
    return languages


def write(name, data):
    out = DATA / name
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return out.relative_to(SITE)


def write_authors(source):
    sections = parse_authors(source)
    data = {"note": NOTE.format("AUTHORS"), "sections": sections}
    print(f"wrote {write('authors.json', data)}: {len(sections)} sections")


def write_translators(source):
    languages = sorted(parse_translators(source).values(), key=lambda l: collation_key(l["language"]))
    people = set()
    data = {"note": NOTE.format("TRANSLATORS"), "languages": []}
    for lang in languages:
        roles = {name: sorted(roles, key=LEAD_ROLES.index) for name, roles in lang["leads"].items()}
        leads = sorted(roles, key=lambda name: (LEAD_ROLES.index(roles[name][0]), collation_key(name)))
        others = sorted(lang["translators"] - roles.keys(), key=collation_key)
        people.update(leads, others)
        data["languages"].append({
            "language": lang["language"],
            "code": lang["code"],
            "leads": [{"name": name, "roles": roles[name]} for name in leads],
            "translators": others,
        })
    data["people"] = len(people)
    print(f"wrote {write('translators.json', data)}: {len(people)} people, {len(languages)} languages")


def main():
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} path/to/retransmission")
    checkout = pathlib.Path(sys.argv[1])
    sources = [checkout / "AUTHORS", checkout / "TRANSLATORS"]
    for source in sources:
        if not source.is_file():
            sys.exit(f"{source} not found")
    write_authors(sources[0])
    write_translators(sources[1])


if __name__ == "__main__":
    main()
