#!/usr/bin/env python3
"""Regenerate _data/translators.yml from a retransmission checkout.

Usage: _scripts/update-credits.py path/to/retransmission

Reads the checkout's TRANSLATORS file, which looks like:

    German (de)
      Lead Translator (lead)
      Client Lead (macOS lead)
      Some Contributor

and writes the credits page's data: languages sorted by name,
each with its leads first and the other translators alphabetical.
"""

import json
import pathlib
import re
import sys
import unicodedata

SITE = pathlib.Path(__file__).resolve().parent.parent
OUT = SITE / "_data" / "translators.yml"

LANGUAGE = re.compile(r"^(?P<name>\S.*) \((?P<code>[a-z]{2,3}(?:_[A-Za-z]+)?(?:@[a-z]+)?)\)$")
LEAD = re.compile(r"^(?P<name>.+?) \((?P<role>(?:(?:GTK|Qt|macOS) )?lead)\)$")
LEAD_ORDER = {"lead": 0, "GTK lead": 1, "Qt lead": 2, "macOS lead": 3}


def collation_key(text):
    """Sort case- and accent-insensitively, so "Émile" files under E."""
    decomposed = unicodedata.normalize("NFKD", text)
    base = "".join(c for c in decomposed if not unicodedata.combining(c))
    return base.casefold(), text


def parse(path):
    languages = {}
    current = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        if not line[0].isspace():
            # A language heading; any other unindented line is preamble.
            current = None
            if match := LANGUAGE.match(line.rstrip()):
                current = languages.setdefault(match["code"], {
                    "language": match["name"], "code": match["code"],
                    "leads": {}, "translators": set(),
                })
            continue
        if current is None:
            continue  # indented text in the file's preamble
        name = line.strip()
        if match := LEAD.match(name):
            current["leads"].setdefault(match["name"], match["role"])
        else:
            current["translators"].add(name)
    if not languages:
        sys.exit(f"{path}: no languages found")
    return languages


def quote(text):
    return json.dumps(text, ensure_ascii=False)  # JSON strings are valid YAML


def main():
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} path/to/retransmission")
    source = pathlib.Path(sys.argv[1]) / "TRANSLATORS"
    if not source.is_file():
        sys.exit(f"{source} not found")

    languages = sorted(parse(source).values(), key=lambda l: collation_key(l["language"]))
    people = set()
    lines = [
        "# Generated by _scripts/update-credits.py from the retransmission",
        "# repo's TRANSLATORS file. Edit that file, not this one.",
        "languages:",
    ]
    for lang in languages:
        leads = sorted(lang["leads"].items(), key=lambda kv: (LEAD_ORDER[kv[1]], collation_key(kv[0])))
        others = sorted(lang["translators"] - lang["leads"].keys(), key=collation_key)
        people.update(lang["leads"], others)
        lines.append(f"  - language: {quote(lang['language'])}")
        lines.append(f"    code: {quote(lang['code'])}")
        lines.append("    leads: [" + ", ".join(
            f"{{name: {quote(name)}, role: {quote(role)}}}" for name, role in leads) + "]")
        lines.append(f"    translators: [{', '.join(map(quote, others))}]")
    lines.append(f"people: {len(people)}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(SITE)}: {len(people)} people, {len(languages)} languages")


if __name__ == "__main__":
    main()
