#!/usr/bin/env python3
"""Regenerate the credits page's data from a retransmission checkout.

Usage: _scripts/update-credits.py path/to/retransmission

Reads the checkout's AUTHORS file, whose sections look like:

    Maintainers
      Some Maintainer (@github-handle)

and writes _data/authors.yml, keeping each section's order.

Reads the checkout's TRANSLATORS file, which looks like:

    German (de)
      Lead Translator (lead)
      Client Lead (macOS lead)
      Some Contributor

and writes _data/translators.yml: languages sorted by name,
each with its leads first and the other translators alphabetical.
"""

import json
import pathlib
import re
import sys
import unicodedata

SITE = pathlib.Path(__file__).resolve().parent.parent
DATA = SITE / "_data"
HEADER = [
    "# Generated by _scripts/update-credits.py from the retransmission",
    "# repo's {} file. Edit that file, not this one.",
]

AUTHOR = re.compile(r"^(?P<name>.+?)(?: \(@(?P<github>[\w-]+)\))?$")

LANGUAGE = re.compile(r"^(?P<name>\S.*) \((?P<code>[a-z]{2,3}(?:_[A-Za-z]+)?(?:@[a-z]+)?)\)$")
LEAD = re.compile(r"^(?P<name>.+?) \((?P<role>(?:(?:GTK|Qt|macOS) )?lead)\)$")
LEAD_ORDER = {"lead": 0, "GTK lead": 1, "Qt lead": 2, "macOS lead": 3}


def collation_key(text):
    """Sort case- and accent-insensitively, so "Émile" files under E."""
    decomposed = unicodedata.normalize("NFKD", text)
    base = "".join(c for c in decomposed if not unicodedata.combining(c))
    return base.casefold(), text


def parse_authors(path):
    """Each unindented heading followed by indented names is a section.
    Prose, and headings ending in ':' (the pre-4.0 contributors paragraph), are skipped."""
    sections = []
    current = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        if not line[0].isspace():
            heading = line.strip()
            current = None if heading.endswith(":") else {"section": heading, "people": []}
            if current:
                sections.append(current)
        elif current is not None:
            current["people"].append(AUTHOR.match(line.strip()).groupdict())
    sections = [s for s in sections if s["people"]]
    if not sections:
        sys.exit(f"{path}: no sections found")
    return sections


def parse_translators(path):
    languages = {}
    current = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        if not line[0].isspace():
            # A language heading; any other unindented line is preamble.
            current = None
            if match := LANGUAGE.match(line.rstrip()):
                current = languages.setdefault(match["code"], {
                    "language": match["name"], "code": match["code"],
                    "leads": {}, "translators": set(),
                })
            continue
        if current is None:
            continue  # indented text in the file's preamble
        name = line.strip()
        if match := LEAD.match(name):
            current["leads"].setdefault(match["name"], match["role"])
        else:
            current["translators"].add(name)
    if not languages:
        sys.exit(f"{path}: no languages found")
    return languages


def quote(text):
    return json.dumps(text, ensure_ascii=False)  # JSON strings are valid YAML


def write(name, lines):
    out = DATA / name
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out.relative_to(SITE)


def write_authors(source):
    sections = parse_authors(source)
    lines = [h.format("AUTHORS") for h in HEADER]
    for section in sections:
        lines.append(f"- section: {quote(section['section'])}")
        lines.append("  people:")
        for person in section["people"]:
            github = quote(person["github"]) if person["github"] else "null"
            lines.append(f"    - {{name: {quote(person['name'])}, github: {github}}}")
    print(f"wrote {write('authors.yml', lines)}: {len(sections)} sections")


def write_translators(source):
    languages = sorted(parse_translators(source).values(), key=lambda l: collation_key(l["language"]))
    people = set()
    lines = [h.format("TRANSLATORS") for h in HEADER] + ["languages:"]
    for lang in languages:
        leads = sorted(lang["leads"].items(), key=lambda kv: (LEAD_ORDER[kv[1]], collation_key(kv[0])))
        others = sorted(lang["translators"] - lang["leads"].keys(), key=collation_key)
        people.update(lang["leads"], others)
        lines.append(f"  - language: {quote(lang['language'])}")
        lines.append(f"    code: {quote(lang['code'])}")
        lines.append("    leads: [" + ", ".join(
            f"{{name: {quote(name)}, role: {quote(role)}}}" for name, role in leads) + "]")
        lines.append(f"    translators: [{', '.join(map(quote, others))}]")
    lines.append(f"people: {len(people)}")
    print(f"wrote {write('translators.yml', lines)}: {len(people)} people, {len(languages)} languages")


def main():
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} path/to/retransmission")
    checkout = pathlib.Path(sys.argv[1])
    sources = [checkout / "AUTHORS", checkout / "TRANSLATORS"]
    for source in sources:
        if not source.is_file():
            sys.exit(f"{source} not found")
    write_authors(sources[0])
    write_translators(sources[1])


if __name__ == "__main__":
    main()
